### ISSUE TITLE
Support installation without CUDA

### ISSUE THREAD

**Issue by vladserkoff** [microsoft/pytorch_od#1]
Hi, @dashesy, thank you for the implementation of batched NMS. Unfortunately, I was not able to install the library on the machine without CUDA. AFAIS, there is a CPU implementation, and it would be nice to be able to use it on the CPU-only machines.
Thanks!
The trace when I try to install it on a machine without CUDA:
```
% pip install git+https://github.com/microsoft/pytorch_od.git
    ..........
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1z/pz_kbcf15gncn6wg3ws9v9qm0000gn/T/pip-req-build-rzwrbl8z/setup.py", line 42, in <module>
        ], include_dirs=include_dirs),
      File "/usr/local/miniconda3/envs/env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 476, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/usr/local/miniconda3/envs/env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 555, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/usr/local/miniconda3/envs/env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1146, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dashesy** [comment]
Should be fixed, lmk if not

**Comment by vladserkoff** [comment]
This https://github.com/microsoft/pytorch_od/blob/cf84773b5e54f45d2aa86f9ac1b5dcd74ee1fe25/setup.py#L10
doesn't seem to guaranty that there's no CUDA on the machine, at least on my machine it imports successfully. How about checking if `torch.cuda.is_available()`?

**Comment by dashesy** [comment]
So it is imported fine, but the error happens when the extension is being built.

**Comment by vladserkoff** [comment]
Hey @dashesy, sorry for bothering again, but there's apparently an undesired side-effect with checking `torch.cuda.is_available()`. When I try to build this extension in docker with cuda in order to run it later on a machine with GPU, this will build a CPU version instead of CUDA.
IDK how to do it correctly, but you should probably try building CUDA version first, and only revert to CPU version if it fails.

**Comment by dashesy** [comment]
You are correct. Unfortunately there is no straightforward way to separate build environment from runtime. I created [this](https://discuss.pytorch.org/t/build-extensions-with-without-cuda/57193) thread but got no response. [Here](https://github.com/pytorch/pytorch/issues/27222) I created an issue to get a more elegant solution, than try-catch the setup() call.

**Comment by vladserkoff** [comment]
Thanks! Seems like your last commit have done the trick. Let's hope the pytorch teem addresses the issue.
